### ISSUE TITLE
¿Sobra alguna variable?

### ISSUE THREAD

**Issue by lmagarin** [R4f4Lc/Examen-Diciembre-DWEC#11]
https://github.com/R4f4Lc/Examen-Diciembre-DWEC/blob/1338d04ce5cf3f025565f4bd416bdfbff09cf3c3/js/detodounpoco.js#L9

```
undefined

Son las 11:53.Pronto llegan las vacaciones. Aguanta
```

**Comment by R4f4Lc** [comment]
Esto ya ha sido arreglado en el issue #8
