### ISSUE TITLE
Formato incorrecto: hh:mm

### ISSUE THREAD

**Issue by lmagarin** [R4f4Lc/Examen-Diciembre-DWEC#12]
https://github.com/R4f4Lc/Examen-Diciembre-DWEC/blob/1338d04ce5cf3f025565f4bd416bdfbff09cf3c3/js/detodounpoco.js#L9

```
undefined

Son las 11:53.Pronto llegan las vacaciones. Aguanta
```

**Comment by R4f4Lc** [comment]
Eso devuelve el dia de la semana(Lunes a Domingo) la fecha se devuelve en getHoraActual()
