### ISSUE TITLE
Error en la fecha

### ISSUE THREAD

**Issue by Javierfs94** [R4f4Lc/Examen-Diciembre-DWEC#4]
https://github.com/R4f4Lc/Examen-Diciembre-DWEC/blob/ac4a89115d3e93508a1b5d62fba5139bd91b0d3d/js/Validar.js#L8

**Comment by Javierfs94** [comment]
No acepta 13/03/1994 como fecha válida, cuando es una fecha válida.

**Comment by R4f4Lc** [comment]
La expresión regular está bien. El problema es que al crear la fecha al hacer un new Date(fechaNacimiento) coge el formato en inglés, entonces hay que transformar la fecha que nos proporciona el usuario a inglés para poder validar la fecha correctamente.
